/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PacketRouteImport } from './routes/packet'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as LoopRouteImport } from './routes/loop'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecordRecordIdRouteImport } from './routes/record.$recordId'
import { Route as DevelopersVisionRouteImport } from './routes/developers/vision'
import { Route as DevelopersRoadmapRouteImport } from './routes/developers/roadmap'
import { Route as DevelopersPrioritizationRouteImport } from './routes/developers/prioritization'
import { Route as DevelopersOverviewRouteImport } from './routes/developers/overview'
import { Route as DevelopersGatingRouteImport } from './routes/developers/gating'

const PacketRoute = PacketRouteImport.update({
  id: '/packet',
  path: '/packet',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const LoopRoute = LoopRouteImport.update({
  id: '/loop',
  path: '/loop',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRecordIdRoute = RecordRecordIdRouteImport.update({
  id: '/record/$recordId',
  path: '/record/$recordId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersVisionRoute = DevelopersVisionRouteImport.update({
  id: '/developers/vision',
  path: '/developers/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoadmapRoute = DevelopersRoadmapRouteImport.update({
  id: '/developers/roadmap',
  path: '/developers/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersPrioritizationRoute =
  DevelopersPrioritizationRouteImport.update({
    id: '/developers/prioritization',
    path: '/developers/prioritization',
    getParentRoute: () => rootRouteImport,
  } as any)
const DevelopersOverviewRoute = DevelopersOverviewRouteImport.update({
  id: '/developers/overview',
  path: '/developers/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersGatingRoute = DevelopersGatingRouteImport.update({
  id: '/developers/gating',
  path: '/developers/gating',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loop': typeof LoopRoute
  '/ops': typeof OpsRoute
  '/packet': typeof PacketRoute
  '/developers/gating': typeof DevelopersGatingRoute
  '/developers/overview': typeof DevelopersOverviewRoute
  '/developers/prioritization': typeof DevelopersPrioritizationRoute
  '/developers/roadmap': typeof DevelopersRoadmapRoute
  '/developers/vision': typeof DevelopersVisionRoute
  '/record/$recordId': typeof RecordRecordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loop': typeof LoopRoute
  '/ops': typeof OpsRoute
  '/packet': typeof PacketRoute
  '/developers/gating': typeof DevelopersGatingRoute
  '/developers/overview': typeof DevelopersOverviewRoute
  '/developers/prioritization': typeof DevelopersPrioritizationRoute
  '/developers/roadmap': typeof DevelopersRoadmapRoute
  '/developers/vision': typeof DevelopersVisionRoute
  '/record/$recordId': typeof RecordRecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/loop': typeof LoopRoute
  '/ops': typeof OpsRoute
  '/packet': typeof PacketRoute
  '/developers/gating': typeof DevelopersGatingRoute
  '/developers/overview': typeof DevelopersOverviewRoute
  '/developers/prioritization': typeof DevelopersPrioritizationRoute
  '/developers/roadmap': typeof DevelopersRoadmapRoute
  '/developers/vision': typeof DevelopersVisionRoute
  '/record/$recordId': typeof RecordRecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/loop'
    | '/ops'
    | '/packet'
    | '/developers/gating'
    | '/developers/overview'
    | '/developers/prioritization'
    | '/developers/roadmap'
    | '/developers/vision'
    | '/record/$recordId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/loop'
    | '/ops'
    | '/packet'
    | '/developers/gating'
    | '/developers/overview'
    | '/developers/prioritization'
    | '/developers/roadmap'
    | '/developers/vision'
    | '/record/$recordId'
  id:
    | '__root__'
    | '/'
    | '/loop'
    | '/ops'
    | '/packet'
    | '/developers/gating'
    | '/developers/overview'
    | '/developers/prioritization'
    | '/developers/roadmap'
    | '/developers/vision'
    | '/record/$recordId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoopRoute: typeof LoopRoute
  OpsRoute: typeof OpsRoute
  PacketRoute: typeof PacketRoute
  DevelopersGatingRoute: typeof DevelopersGatingRoute
  DevelopersOverviewRoute: typeof DevelopersOverviewRoute
  DevelopersPrioritizationRoute: typeof DevelopersPrioritizationRoute
  DevelopersRoadmapRoute: typeof DevelopersRoadmapRoute
  DevelopersVisionRoute: typeof DevelopersVisionRoute
  RecordRecordIdRoute: typeof RecordRecordIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/packet': {
      id: '/packet'
      path: '/packet'
      fullPath: '/packet'
      preLoaderRoute: typeof PacketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loop': {
      id: '/loop'
      path: '/loop'
      fullPath: '/loop'
      preLoaderRoute: typeof LoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record/$recordId': {
      id: '/record/$recordId'
      path: '/record/$recordId'
      fullPath: '/record/$recordId'
      preLoaderRoute: typeof RecordRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/vision': {
      id: '/developers/vision'
      path: '/developers/vision'
      fullPath: '/developers/vision'
      preLoaderRoute: typeof DevelopersVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/roadmap': {
      id: '/developers/roadmap'
      path: '/developers/roadmap'
      fullPath: '/developers/roadmap'
      preLoaderRoute: typeof DevelopersRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/prioritization': {
      id: '/developers/prioritization'
      path: '/developers/prioritization'
      fullPath: '/developers/prioritization'
      preLoaderRoute: typeof DevelopersPrioritizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/overview': {
      id: '/developers/overview'
      path: '/developers/overview'
      fullPath: '/developers/overview'
      preLoaderRoute: typeof DevelopersOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/gating': {
      id: '/developers/gating'
      path: '/developers/gating'
      fullPath: '/developers/gating'
      preLoaderRoute: typeof DevelopersGatingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoopRoute: LoopRoute,
  OpsRoute: OpsRoute,
  PacketRoute: PacketRoute,
  DevelopersGatingRoute: DevelopersGatingRoute,
  DevelopersOverviewRoute: DevelopersOverviewRoute,
  DevelopersPrioritizationRoute: DevelopersPrioritizationRoute,
  DevelopersRoadmapRoute: DevelopersRoadmapRoute,
  DevelopersVisionRoute: DevelopersVisionRoute,
  RecordRecordIdRoute: RecordRecordIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
